#include "hds_quasiplanar.h"
#include <fstream>
#include <vector>
#include <algorithm>
#include <iostream>
#include <cassert>
#include <set>
#include <string>

typedef std::vector<std::size_t> Edge;
typedef std::vector<Edge> Edges;
typedef std::pair<std::size_t, std::size_t> VPair;

// G+(i,j): K10 plus x = 10, y = 11, both adjacent to the same 6-set N of the K10 vertices.
// mode (first argument):
//   base:    find a drawing of G+(i,j)
//   x-only:  only add x, count the 6-sets for which this works (sanity check)
//   plus-xy: G+(i,j) + (x,y)
//   plus-xb: G+(i,j) + (x,b) for b outside N
//   all:     all drawings of G+(i,j), test each for saturation, write them to all_drawings.txt
const std::size_t n = 12;
const std::size_t klim = 17;
const int num_drawings = 9;

// one 6-subset of {0..9} per orbit of the automorphism group of K10 drawing i (the smallest bitmask):
// Aut of drawings 0-7 is trivial, drawing 8 has Aut = C10, generated by (0 2 4 6 7 9 3 1 5 8)
std::vector<Edge> six_sets(int drawing) {
    std::vector<std::size_t> id = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
    std::vector<std::vector<std::size_t>> group = {id};
    if (drawing == 8) {
        const std::vector<std::size_t> cycle = {0, 2, 4, 6, 7, 9, 3, 1, 5, 8};
        std::vector<std::size_t> g(10);
        for (std::size_t k = 0; k < 10; ++k) g[cycle[k]] = cycle[(k + 1) % 10];
        for (int k = 1; k < 10; ++k) {
            for (std::size_t v = 0; v < 10; ++v) id[v] = g[id[v]];
            group.push_back(id);
        }
    }

    std::vector<Edge> reps;
    for (unsigned mask = 0; mask < (1u << 10); ++mask) {
        if (__builtin_popcount(mask) != 6) continue;
        bool smallest = true;
        for (const auto& g : group) {
            unsigned img = 0;
            for (std::size_t v = 0; v < 10; ++v) if (mask >> v & 1) img |= 1u << g[v];
            if (img < mask) smallest = false;
        }
        if (!smallest) continue;
        Edge N;
        for (std::size_t v = 0; v < 10; ++v) if (mask >> v & 1) N.push_back(v);
        reps.push_back(N);
    }
    return reps;
}

// non-edges that can be inserted into d (d is unchanged afterwards)
std::vector<VPair> insertable_non_edges(Drawing<klim>& d) {
    std::set<VPair> present;
    for (const auto& e : d.edges) present.insert(std::minmax(e.u, e.v));
    std::vector<VPair> res;
    for (std::size_t u = 0; u < n; ++u) {
        for (std::size_t v = u + 1; v < n; ++v) {
            if (present.count({u, v})) continue;
            for (HdsPath p = d.first_path(u, v); !p.empty();) {
                d.add_edge(p, v);
                bool quasi = d.verify_quasiplanarity();
                p = d.edges.back().built;
                d.remove_edge();
                if (quasi) { res.push_back({u, v}); break; }
                if (!d.next_path(p, v)) break;
            }
        }
    }
    return res;
}

void save(const Drawing<klim>& d, const std::string& name) {
    std::ofstream(name + ".json") << d.serialize_to_json().dump(4);
    std::ofstream gml(name + ".graphml");
    d.graphml_output(gml);
}

int main(int argc, char** argv) {
    const std::string mode = argc > 1 ? argv[1] : "base";
    std::cout << "\n\n ===================================================== \n";
    std::cout << "K10 + x,y, k = " << klim << ", n = " << n << ", mode = " << mode << std::endl;

    std::ofstream all_out;
    if (mode == "all") all_out.open("all_drawings.txt"); // one drawing per line, "S " = saturated, "E " = extensible
    std::size_t total = 0, saturated = 0;

    for (int i = 0; i < num_drawings; ++i) {
        std::ifstream input_file("../quasiDrawings/K10_all_quasi/" + std::to_string(i) + ".json");
        if (!input_file.is_open()) {
            std::cerr << "Could not open drawing file " << i << std::endl;
            continue;
        }
        nlohmann::json import_data;
        input_file >> import_data;
        input_file.close();

        std::vector<Edge> sets = six_sets(i);
        std::cout << "Drawing " << i << ": " << sets.size() << " 6-sets" << std::endl;

        for (const Edge& N : sets) {
            // b = 10 means no extra neighbour of x
            for (std::size_t b = 0; b <= 10; ++b) {
                if (mode == "plus-xb" ? (b == 10 || std::count(N.begin(), N.end(), b)) : b != 10) continue;

                Edges edges;
                for (std::size_t v : N) edges.push_back({v, 10});
                if (b < 10) edges.push_back({b, 10});
                if (mode == "plus-xy") edges.push_back({10, 11});
                if (mode != "x-only")
                    for (std::size_t v : N) edges.push_back({v, 11});

                Drawing<klim> d(import_data, n);
                auto start_edge = edges.begin();

                for (auto e = start_edge;;) {
                    std::size_t u = (*e)[0];
                    std::size_t v = (*e)[1];
                    HdsPath p = d.first_path(u, v);

                    if (p.empty()) {
BACKUP:
                        do {
                            if (e == start_edge) {
                                goto NEXT_ITEM;
                            }
                            --e;

                            u = (*e)[0];
                            assert(u == d.edges.back().u);
                            v = (*e)[1];
                            assert(v == d.edges.back().v);
                            p = d.edges.back().built;
                            d.remove_edge();
                        } while (!d.next_path(p, v));
                    }
                    d.add_edge(p, v);

                    if (++e == edges.end()) {
                        assert(d.verify_quasiplanarity());
                        std::vector<VPair> ins = insertable_non_edges(d);
                        ++total;
                        if (ins.empty()) ++saturated;

                        if (mode == "all") {
                            all_out << (ins.empty() ? "S " : "E ") << d.serialize_to_json().dump() << "\n";
                            goto BACKUP; // continue with the next drawing
                        }
                        if (mode == "x-only") goto NEXT_ITEM; // only count

                        std::string name = "k10_plus_two_" + mode + "_" + std::to_string(i) + "_" + std::to_string(total);
                        save(d, name);
                        std::cout << "Found drawing (saved " << name << "), insertable non-edges:";
                        for (const auto& [a, c] : ins) std::cout << " (" << a << "," << c << ")";
                        std::cout << (ins.empty() ? " none, saturated" : "") << std::endl;
                        return 0;
                    }
                }
NEXT_ITEM:;
            }
        }
    }

    if (mode == "all")
        std::cout << "Drawings (labelled): " << total << ", saturated: " << saturated << std::endl;
    else
        std::cout << "Found " << total << " drawings for mode " << mode << std::endl;
    return 0;
}
